# https://kubernetes.io/docs/concepts/services-networking/ingress/#the-ingress-resource

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: IngressName
  namespace: default
spec:
  rules:
  - host: bermtec.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: walmartpaymentservice
            port:
              number: 80