apiVersion: v1
kind: Service
metadata:
  name: walmartpaymentservice
  namespace: default
spec:
  selector:
    app: walmartpayment-dev
  type: ClusterIP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: http-port
    protocol: TCP
    port: 80
    targetPort: 5000
    # If you set the `spec.type` field to `NodePort` and you want a specific port number,
    # you can specify a value in the `spec.ports[*].nodePort` field.
    nodePort: 32000